services:
  mongodb:
    image: mongo:latest
    container_name: pizza-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  pizza-app:
    build: .
    container_name: pizza-counter-app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./videos:/app/videos
      - ./models:/app/models
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/pizza_counter?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongodb_data: